<% if('mongo' == database ){ %>
mongo:
  restart: always
  image: tutum/mongodb
  volumes:
    - /data/db:/opt/db
  ports:
    - "27017:27017"
  environment:
    - MONGODB_DATABASE=mydatabase
    - MONGODB_USER=user
    - MONGODB_PASS=mypass
  command: /run.sh --smallfiles
  <% } %>
<%=baseName %>:
  restart: always
  image: <%=baseName %>
  ports:
    - "3000:3000"<% if('mongo' == database || 'yes' == messaging ){ %>
  environment:<% if('mongo' == database ){ %>
    - MONGODB_DATABASE=mydatabase
    - MONGODB_USER=user
    - MONGODB_PASS=mypass <% } %><% if('yes' == messaging) { %>
    - MESSAGING_LOGIN=admin
    - MESSAGING_PASSWORD=admin <% } %>
    <% } %>
    <% if('mongo' == database || 'yes' == messaging ){ %>
  links:
    <% } %>
  <% if('mongo' == database ){ %>
    - mongo
  <% } %>
  <% if('yes' == messaging) { %>
    - activemq
  <% } %>
<% if('yes' == messaging) { %>
activemq:
  restart: always
  image: webcenter/activemq
  ports:
    - "61613:61613"
  environment:
    - ACTIVEMQ_ADMIN_LOGIN=admin
    - ACTIVEMQ_ADMIN_PASSWORD=admin
<% } %>


